### ISSUE TITLE
Possibly hand off module to another maintainer

### ISSUE THREAD

**Issue by haarg** [kingpong/perl-Test-Spec#20]
Looking through the other tickets on this module, I noticed that you aren't actively using perl or the module anymore.  Perhaps you'd like to hand the module off for someone else to maintain?  I'm not interested myself, but others might be.

If you did want to give the module to someone else, the way to indicate that is granting the PAUSE user HANDOFF comaintainership of the module.  You can read more about this in the [Lancaster Consensus](https://github.com/Perl-Toolchain-Gang/toolchain-site/blob/master/lancaster-consensus.md#flagging-abandoned-modules-and-modules-requesting-help) document.

**Comment by kingpong** [comment]
This is helpful information, thanks. I'll consider handing it off.

**Comment by kingpong** [comment]
@andyjones Are you by any chance interested in maintaining Test::Spec? It's clear from your contributions that you're capable, and since you're using the module you have some incentive.

If you're not interested, I will do the HANDOFF dance as OP suggested.

Thanks for your recent contributions. `with_deep` is in 0.49 which should be on CPAN now.

**Comment by andyjones** [comment]
Sure, happy to help. I have just requested a pause id.

Thanks for the release

**Comment by kingpong** [comment]
@andyjones I've given you a commit bit for this repository.  Let me know what your PAUSE ID is and I'll assign rights there also.

**Comment by andyjones** [comment]
Thanks, I'm ANDYJONES on PAUSE

**Comment by kingpong** [comment]
@andyjones all set.  I left myself listed as co-maintainer according to PAUSE.  Thanks very much. I'm glad somebody cares enough about it to take it on.

**Comment by andyjones** [comment]
excellent, thank you

**Comment by andyjones** [comment]
@kingpong Sorry any chance you can check the permssions? I think I have co-maints on Test::Spec::* but not Test::Spec itself?

Got the following error from pause:

```
Status: Permission missing
==========================

module : Test::Spec
version: 0.50
in file: Test-Spec-0.50/lib/Test/Spec.pm
status : Not indexed because permission missing. Current registered
primary maintainer is PHILIP. Hint: you can always find the
legitimate maintainer(s) on PAUSE under "View Permissions".
```

**Comment by kingpong** [comment]
Sorry 'bout that. I think I've fixed it now. Let me know if you still have
trouble.

**Comment by andyjones** [comment]
Thanks, hopefully worked this time!
