### ISSUE TITLE
Objects cleaned up during global destruction

### ISSUE THREAD

**Issue by JRaspass** [kingpong/perl-Test-Spec#24]
At $WORK, we use Test::Spec with objects that do tear-down in Moo DEMOLISH blocks. These objects are being destroyed in the global destruction phase; this is an issue because you can't assume predictable order of destruction in this phase ( see: http://www.perlmonks.org/?node_id=166791 ).

The code below illustrates this issue, $y is destroyed in the RUN phase, $x is destroyed in the DESTRUCT phase ( see: http://perldoc.perl.org/perlvar.html#Variables-related-to-the-interpreter-state ).

```perl
use Test::Spec;

sub foo::DESTROY { warn "$_[0]{name} ${^GLOBAL_PHASE}\n" }

describe a => sub {
    my $x = bless { name => 'x' }, 'foo';
    my $y = bless { name => 'y' }, 'foo';

    it b => sub {
        # $x is destroyed during global destruction,
        # because there is a circular ref?
        ok ref $x;
    };

    # $y is destroyed here.
};

runtests unless caller;
```

The above when executed prints:

```
$ prove -v leak.t 
leak.t .. y RUN

ok 1 - a b
1..1
x DESTRUCT
```

We would like to find a way to get the same clean-up behaviour that $y exhibits for $x. Our current *hack* involves creating the objects outside of the outer describe and only using weakened references inside.

**Comment by andyjones** [comment]
`it` blocks are kept around so they can be run later when you call runtests. They won't go out of scope until your program exits so it will keep `$x` alive.

You may be able to use before/after blocks as an alternative to weaken?

I'll think it should be possible for Test::Spec to clear the tests by using an END block but I have been playing for an hour and not had any joy yet.

I'll take another look at the weekend, hope that is okay.

**Comment by andyjones** [comment]
Sorry, this is still in progress. I tracked down a few of the leaks over the weekend but at least one is still eluding me. I'll continue looking

**Comment by JRaspass** [comment]
No worries, thanks for taking the time to look at this.

**Comment by andyjones** [comment]
I think I have tracked them all down so objects should go out of scope after runtests() has finished.

This should be on cpan as 0.50 soon

**Comment by JRaspass** [comment]
This fix worked perfectly, was able to remove all use of Scalar::Util::weaken at $WORK, thanks :+1:
