### ISSUE TITLE
runtests(@patterns) does not work as specified

### ISSUE THREAD

**Issue by mpw96** [kingpong/perl-Test-Spec#38]
Hi,
documentation states: "Runs all the examples whose descriptions match one of the (non case-sensitive) regular expressions in @patterns."

In fact, it runs only thoes examples whose descriptions mach ALL regular expressions.

[Fix](https://github.com/kingpong/perl-Test-Spec/pull/37) provided.

Regards
Marc-Philip

**Comment by andyjones** [comment]
Thank you! 0.52 should be on cpan shortly
