### ISSUE TITLE
META.json in release doesn't include runtime requirements

### ISSUE THREAD

**Issue by joelrebel** [kingpong/perl-Test-Spec#39]
Please update https://metacpan.org/source/ANDYJONES/Test-Spec-0.51/META.json to include the dependencies listed in Makefile.PL.
Systems (rpm build tooling/others) that depend on this file to figure the dependency tree are unable to statically determine the list of dependencies for this distribution, MetaCPAN doesn't report the dependencies either.

Thanks!

**Comment by andyjones** [comment]
Thanks! Fixed in v0.52 by upgrading to a newer version of ExtUtils::MakeMaker
